version: "2.4"
services:
    db:
        image: mysql:8.0
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - ./docker/mysql/data:/var/lib/mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "33066:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
